# GET http://localhost:3000/ HTTP/1.1

GET http://localhost:3000/user/2 HTTP/1.1

# POST http://localhost:3000/create HTTP/1.1
# Content-Type: application/json

# {
#     "name":"张三",
#     "age":18,
#     "hobby": "篮球"
# }

# 更新数据
# POST http://localhost:3000/update HTTP/1.1
# Content-Type: application/json

# {
#     "name":"法外狂徒",
#     "age":20,
#     "hobby": "rap",
#     "id":1
# }
# # 删除
# POST http://localhost:3000/delete HTTP/1.1
# Content-Type: application/json

# {
#     "id":1
# }